from pathlib import Path

from app.api.chat import chat_endpoint
from app.core.models import ChatRequest
from app.eval import EvaluationV2Evaluator
from app.rag.ingestion import MarkdownIngestionPipeline
from app.rag.retriever import LocalKnowledgeRetriever


def _write(path: Path, content: str) -> None:
    path.write_text(content.strip() + "\n", encoding="utf-8")


def test_doc_type_uses_layered_chunk_strategy(tmp_path):
    _write(tmp_path / "guide.md", "# Guide\n" + "\n".join(f"normal paragraph {idx}" for idx in range(80)))
    _write(tmp_path / "service.log", "\n".join(f"2026-01-01 ERROR E50{idx % 5} order-service failed" for idx in range(80)))

    chunks = MarkdownIngestionPipeline(tmp_path, chunk_size=120).ingest()
    markdown_chunks = [chunk for chunk in chunks if chunk.doc_type == "markdown_doc"]
    log_chunks = [chunk for chunk in chunks if chunk.doc_type == "log_file"]

    assert markdown_chunks
    assert log_chunks
    assert len(log_chunks) > len(markdown_chunks)
    assert all(chunk.line_range for chunk in chunks)
    assert all(chunk.content_hash for chunk in chunks)


def test_log_config_code_files_use_fine_grained_chunks(tmp_path):
    _write(tmp_path / "app.log", "\n".join(f"ERROR 500 trace_id={idx} order-service timeout" for idx in range(24)))
    _write(tmp_path / "prod.yaml", "\n".join(f"order.timeout.{idx}: {idx}" for idx in range(24)))
    _write(
        tmp_path / "handler.py",
        "\n".join(
            [
                "class OrderHandler:",
                "    def handle_order(self):",
                "        raise TimeoutError('E500 order-service')",
            ]
            * 8
        ),
    )

    chunks = MarkdownIngestionPipeline(tmp_path, chunk_size=180).ingest()

    assert {chunk.doc_type for chunk in chunks} >= {"log_file", "config_file", "code_file"}
    assert all(len(chunk.content) < 900 for chunk in chunks if chunk.doc_type in {"log_file", "config_file", "code_file"})
    assert any("order.timeout.1:" in chunk.content for chunk in chunks)
    assert any("def handle_order" in chunk.content for chunk in chunks)


def test_duplicate_template_text_is_filtered(tmp_path):
    duplicated = "Generated by system\nCommon troubleshooting template.\nAll rights reserved"
    _write(tmp_path / "runbook-a.txt", duplicated)
    _write(tmp_path / "runbook-b.txt", duplicated)

    pipeline = MarkdownIngestionPipeline(tmp_path, chunk_size=20)
    chunks = pipeline.ingest()

    assert chunks
    assert pipeline.duplicated_count >= 1


def test_keyword_rerank_promotes_error_code_chunk(tmp_path):
    _write(
        tmp_path / "generic.md",
        "# Generic\norder-service has normal deployment notes and general retry advice.",
    )
    _write(
        tmp_path / "incident.log",
        "2026-01-01 ERROR 503 order-service upstream timeout trace_id=abc",
    )

    result = LocalKnowledgeRetriever(docs_dir=tmp_path).retrieve(
        "order-service 503 timeout",
        top_k=2,
        score_threshold=0.0,
        retrieval_type="hybrid",
    )

    assert result["rerank_applied"] is True
    assert result["documents"][0]["source"].endswith("incident.log")
    assert result["documents"][0]["rerank_score"] > 0
    assert "error_code_match" in result["documents"][0]["match_reason"]


def test_rag_evidence_preserves_source_title_chunk_id_and_line_range(tmp_path):
    _write(tmp_path / "incident.log", "ERROR 500 order-service failed\nstacktrace line")

    result = LocalKnowledgeRetriever(docs_dir=tmp_path).retrieve(
        "order-service 500",
        top_k=1,
        score_threshold=0.0,
    )
    doc = result["documents"][0]

    assert doc["source"].endswith("incident.log")
    assert doc["title"] == "incident"
    assert doc["chunk_id"]
    assert doc["line_range"] == [1, 2]
    assert doc["content_hash"]


def test_missing_source_or_title_affects_missing_source_count():
    payload = {
        "query": "order-service 500",
        "answer": "fallback",
        "tool_results": [
            {
                "tool": "rag_retriever",
                "tool_name": "rag_retriever",
                "documents": [
                    {"source": "incident.log", "title": "incident", "content": "ERROR 500"},
                    {"content": "missing metadata"},
                ],
                "rag_metadata": {"grounding_status": "grounded"},
            }
        ],
        "trace": {"steps": []},
    }

    report = EvaluationV2Evaluator().evaluate(payload)

    assert report.rag.missing_source_count == 1
    assert report.rag.source_coverage == 0.5


def test_evaluation_v2_aggregates_rag_v2_metrics():
    payload = {
        "run_id": "rag-v2",
        "query": "order-service 500",
        "answer": "fallback",
        "tool_results": [
            {
                "tool": "rag_retriever",
                "tool_name": "rag_retriever",
                "documents": [{"source": "incident.log", "title": "incident", "content": "ERROR 500"}],
                "rag_metadata": {
                    "grounding_status": "grounded",
                    "precision_at_k": 0.5,
                    "recall_at_k": 1.0,
                    "source_coverage": 1.0,
                    "rerank_applied": True,
                    "dedup_count": 2,
                    "grounded_answer_rate": 1.0,
                },
            }
        ],
        "trace": {"steps": []},
    }

    report = EvaluationV2Evaluator().evaluate(payload)

    assert report.rag.precision_at_k == 0.5
    assert report.rag.recall_at_k == 1.0
    assert report.rag.source_coverage == 1.0
    assert report.rag.rerank_applied is True
    assert report.rag.dedup_count == 2


def test_llm_disabled_full_chain_still_runs(monkeypatch):
    monkeypatch.setenv("LLM_ENABLED", "false")

    data = chat_endpoint(ChatRequest(query="port already in use 服务启动失败")).model_dump()

    assert data["answer_source"] == "fallback"
    assert data["llm_used"] is False
    executor_step = [step for step in data["trace"]["steps"] if step["stage"] == "executor"][0]
    assert executor_step["rerank_applied"] is True
    assert executor_step["dedup_count"] >= 0
